//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceDeskYULI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBServiceDeskEntities : DbContext
    {
        public DBServiceDeskEntities()
            : base("name=DBServiceDeskEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TBL_ADMIN> TBL_ADMIN { get; set; }
        public virtual DbSet<TBL_CARI> TBL_CARI { get; set; }
        public virtual DbSet<TBL_CATEGORY> TBL_CATEGORY { get; set; }
        public virtual DbSet<TBL_DEPARTMENT> TBL_DEPARTMENT { get; set; }
        public virtual DbSet<TBL_EMPLOYEE> TBL_EMPLOYEE { get; set; }
        public virtual DbSet<TBL_INVOICEDETAIL> TBL_INVOICEDETAIL { get; set; }
        public virtual DbSet<TBL_INVOICEINFO> TBL_INVOICEINFO { get; set; }
        public virtual DbSet<TBL_ISSUEDETAIL> TBL_ISSUEDETAIL { get; set; }
        public virtual DbSet<TBL_NOTES> TBL_NOTES { get; set; }
        public virtual DbSet<TBL_PRODUCTACCEPT> TBL_PRODUCTACCEPT { get; set; }
        public virtual DbSet<TBL_PRODUCTINFO> TBL_PRODUCTINFO { get; set; }
        public virtual DbSet<TBL_PRODUCTMOVEMENT> TBL_PRODUCTMOVEMENT { get; set; }
        public virtual DbSet<TBL_PRODUCTRACKING> TBL_PRODUCTRACKING { get; set; }
    }
}
