//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceDeskYULI
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PRODUCTINFO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_PRODUCTINFO()
        {
            this.TBL_PRODUCTACCEPT = new HashSet<TBL_PRODUCTACCEPT>();
            this.TBL_PRODUCTMOVEMENT = new HashSet<TBL_PRODUCTMOVEMENT>();
            this.TBL_PRODUCTRACKING = new HashSet<TBL_PRODUCTRACKING>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string BRAND { get; set; }
        public Nullable<decimal> BUY { get; set; }
        public Nullable<decimal> SELL { get; set; }
        public Nullable<short> STOCK { get; set; }
        public Nullable<byte> CATOGORY { get; set; }
        public Nullable<bool> STATUS { get; set; }
    
        public virtual TBL_CATEGORY TBL_CATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_PRODUCTACCEPT> TBL_PRODUCTACCEPT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_PRODUCTMOVEMENT> TBL_PRODUCTMOVEMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_PRODUCTRACKING> TBL_PRODUCTRACKING { get; set; }
    }
}
