//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceDeskYULI
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PRODUCTMOVEMENT
    {
        public int MOVEMENTID { get; set; }
        public Nullable<int> PRODUCT { get; set; }
        public Nullable<int> CLIENT { get; set; }
        public Nullable<short> EMPLOYEE { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<short> QUANTITY { get; set; }
        public Nullable<decimal> PRICE { get; set; }
    
        public virtual TBL_CARI TBL_CARI { get; set; }
        public virtual TBL_PRODUCTINFO TBL_PRODUCTINFO { get; set; }
    }
}
