//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceDeskYULI
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ISSUEDETAIL
    {
        public int ISSUEID { get; set; }
        public Nullable<int> PROCCESS { get; set; }
        public string ISSUE { get; set; }
        public string EXPLANATION { get; set; }
        public Nullable<decimal> PREPRICE { get; set; }
        public Nullable<decimal> CURRENTPRICE { get; set; }
        public string OPERATIONS { get; set; }
    }
}
