//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceDeskYULI
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CARI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_CARI()
        {
            this.TBL_INVOICEINFO = new HashSet<TBL_INVOICEINFO>();
            this.TBL_PRODUCTACCEPT = new HashSet<TBL_PRODUCTACCEPT>();
            this.TBL_PRODUCTMOVEMENT = new HashSet<TBL_PRODUCTMOVEMENT>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string LASTNAME { get; set; }
        public string TELEPHONE { get; set; }
        public string MAIL { get; set; }
        public string COUNTRY { get; set; }
        public string CITY { get; set; }
        public string BANK { get; set; }
        public string VAT { get; set; }
        public string VATNO { get; set; }
        public string STATU { get; set; }
        public string ADDRESS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_INVOICEINFO> TBL_INVOICEINFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_PRODUCTACCEPT> TBL_PRODUCTACCEPT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_PRODUCTMOVEMENT> TBL_PRODUCTMOVEMENT { get; set; }
    }
}
