//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceDeskYULI
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PRODUCTRACKING
    {
        public int TRACKINGID { get; set; }
        public Nullable<int> PRODUCT { get; set; }
        public string STATUS { get; set; }
        public Nullable<int> DATA { get; set; }
        public string TRACKINGCODE { get; set; }
    
        public virtual TBL_PRODUCTINFO TBL_PRODUCTINFO { get; set; }
    }
}
